const data = {
  products: [
    {
      _id: '1',
      name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
      slug: 'adidas-1',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      slug: 'adidas-2',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      slug: 'adidas-3',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      slug: 'adidas-4',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      slug: 'adidas-5',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      slug: 'adidas-6',
      category: 'Pants',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};

export default data;
